#!/usr/bin/env python3
"""
AI blog image generator for amortcalc.io — YMYL-financial mortgage/loan articles.
Generates the 12 inline body images (2 per article, 6 articles).
Hero images were already generated by ai_generate_blog_images_phase2.py.

Uses ERNIE-Image-Turbo. Generates at 1024x1024, center-crops to target size.

Usage:
    /data/venvs/ai-image-gen/bin/python3.11 scripts/ai_generate_blog_images_amortcalc.py --test
    /data/venvs/ai-image-gen/bin/python3.11 scripts/ai_generate_blog_images_amortcalc.py --all
"""

import argparse
import hashlib
import os
import sys
import time

from PIL import Image

# ---------------------------------------------------------------------------
# Image manifest — 12 inline body images for 6 amortcalc.io YMYL-financial articles
# ---------------------------------------------------------------------------
# size "body" -> 900x500 (inline article image)
BLOG_IMAGES = [
    # Article 1 — 15-year-vs-30-year-mortgage
    {
        "slug": "15-year-vs-30-year-mortgage-1",
        "size": "body",
        "prompt": (
            "Bar chart comparing total interest paid over the life of a 15-year mortgage "
            "versus a 30-year mortgage, 15-year bar clearly shorter showing less total interest, "
            "clean professional financial data visualization, blue-grey palette, "
            "white background, labeled dollar amounts on bars, no people"
        ),
    },
    {
        "slug": "15-year-vs-30-year-mortgage-2",
        "size": "body",
        "prompt": (
            "Dual line graph showing monthly payment amount on y-axis versus loan term years on x-axis, "
            "two distinct lines for 15-year and 30-year mortgage payment trajectories, "
            "clean professional financial chart, blue-grey color scheme, "
            "white background, labeled axes and legend, no people"
        ),
    },
    # Article 2 — amortization-schedule-explained
    {
        "slug": "amortization-schedule-explained-1",
        "size": "body",
        "prompt": (
            "Stacked horizontal bar chart showing interest portion versus principal portion "
            "for mortgage payments at different loan stages, "
            "interest shown in grey and principal in blue-teal, "
            "clean professional financial infographic, white background, "
            "labeled percentages and years, no people"
        ),
    },
    {
        "slug": "amortization-schedule-explained-2",
        "size": "body",
        "prompt": (
            "Area chart showing month-by-month remaining loan balance declining from full amount "
            "down to zero over 30 years, smooth declining curve, "
            "clean professional mortgage balance visualization, "
            "blue gradient fill under curve, white background, labeled axes, no people"
        ),
    },
    # Article 3 — extra-mortgage-payments
    {
        "slug": "extra-mortgage-payments-1",
        "size": "body",
        "prompt": (
            "Timeline comparison infographic showing standard mortgage payoff timeline "
            "versus accelerated payoff timeline with extra payments, "
            "shorter bar or arrow clearly indicating years saved, "
            "clean professional financial comparison chart, blue-grey palette, "
            "white background, labeled year savings, no people"
        ),
    },
    {
        "slug": "extra-mortgage-payments-2",
        "size": "body",
        "prompt": (
            "Calculator-style infographic showing interest savings from making extra mortgage payments, "
            "large dollar amount saved displayed prominently, "
            "clean professional financial savings visualization, "
            "dark navy and teal on white background, clean typography, no people"
        ),
    },
    # Article 4 — how-amortization-works
    {
        "slug": "how-amortization-works-1",
        "size": "body",
        "prompt": (
            "Pie chart showing early mortgage payment composition split with large interest slice "
            "in grey and small principal slice in blue-teal, "
            "front-loading concept visualization, professional financial infographic, "
            "clean minimal design, white background, labeled percentages, no people"
        ),
    },
    {
        "slug": "how-amortization-works-2",
        "size": "body",
        "prompt": (
            "Side-by-side pie charts comparing early year payment split versus late year payment split, "
            "left pie dominated by interest in grey, right pie dominated by principal in blue, "
            "equal monthly payment with shifting interest-principal ratio concept, "
            "clean professional financial infographic, white background, labeled, no people"
        ),
    },
    # Article 5 — interest-vs-principal
    {
        "slug": "interest-vs-principal-1",
        "size": "body",
        "prompt": (
            "Two side-by-side bar comparisons showing month 1 mortgage payment breakdown "
            "versus month 60 mortgage payment breakdown, "
            "interest portion shown in grey shrinking and principal in blue growing, "
            "clean professional financial comparison infographic, "
            "white background, labeled amounts and percentages, no people"
        ),
    },
    {
        "slug": "interest-vs-principal-2",
        "size": "body",
        "prompt": (
            "Donut chart showing total mortgage cost breakdown with interest paid portion "
            "and principal repaid portion labeled with dollar amounts, "
            "total cost of borrowing visualization, clean professional financial infographic, "
            "blue-grey color palette, white background, labeled segments, no people"
        ),
    },
    # Article 6 — what-is-amortization
    {
        "slug": "what-is-amortization-1",
        "size": "body",
        "prompt": (
            "Simple descending step bar chart or line graph showing mortgage loan balance "
            "declining from full loan amount down toward zero over time, "
            "clean professional financial visualization, "
            "blue-teal gradient bars on white background, labeled year milestones, no people"
        ),
    },
    {
        "slug": "what-is-amortization-2",
        "size": "body",
        "prompt": (
            "Lifecycle diagram of a mortgage loan from origination through monthly payments "
            "to full payoff, horizontal timeline with labeled phases and milestones, "
            "clean professional financial process infographic, "
            "blue-grey corporate design, white background, no people"
        ),
    },
]

SIZES = {
    "body": (900, 500),
}

# ---------------------------------------------------------------------------
# Pipeline (lazy-loaded)
# ---------------------------------------------------------------------------
_pipe = None


def get_pipeline():
    global _pipe
    if _pipe is None:
        os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")
        print("Loading ERNIE-Image-Turbo...", file=sys.stderr)
        from diffusers import ErnieImagePipeline
        from diffusers.quantizers.pipe_quant_config import PipelineQuantizationConfig
        from transformers import AutoModel, AutoModelForCausalLM, BitsAndBytesConfig
        import torch
        import gc

        bnb_4bit = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_compute_dtype=torch.bfloat16,
            bnb_4bit_use_double_quant=True,
        )
        quant_config = PipelineQuantizationConfig(
            quant_backend="bitsandbytes_4bit",
            quant_kwargs={
                "load_in_4bit": True,
                "bnb_4bit_compute_dtype": torch.bfloat16,
                "bnb_4bit_use_double_quant": True,
            },
            components_to_quantize=["transformer"],
        )

        _pipe = ErnieImagePipeline.from_pretrained(
            "baidu/ERNIE-Image-Turbo",
            torch_dtype=torch.bfloat16,
            quantization_config=quant_config,
            cache_dir="/data/huggingface",
        )

        snap_dir = [
            d
            for d in os.listdir(
                "/data/huggingface/models--baidu--ERNIE-Image-Turbo/snapshots/"
            )
            if not d.startswith(".")
        ][0]
        snap_path = (
            f"/data/huggingface/models--baidu--ERNIE-Image-Turbo/snapshots/{snap_dir}"
        )

        del _pipe.text_encoder
        gc.collect()
        _pipe.text_encoder = AutoModel.from_pretrained(
            f"{snap_path}/text_encoder",
            quantization_config=bnb_4bit,
            torch_dtype=torch.bfloat16,
            device_map="auto",
        )

        del _pipe.pe
        gc.collect()
        _pipe.pe = AutoModelForCausalLM.from_pretrained(
            f"{snap_path}/pe",
            quantization_config=bnb_4bit,
            torch_dtype=torch.bfloat16,
            device_map="auto",
        )

        _pipe.transformer = _pipe.transformer.to("cuda:0")
        _pipe.vae = _pipe.vae.to("cuda:0")
        print(
            f"Pipeline ready. GPU0: {torch.cuda.mem_get_info(0)[1]/1e9:.1f}GB, "
            f"GPU1: {torch.cuda.mem_get_info(1)[1]/1e9:.1f}GB",
            file=sys.stderr,
        )
    return _pipe


# ---------------------------------------------------------------------------
# Core generation
# ---------------------------------------------------------------------------
def center_crop_to_ratio(img: Image.Image, target_w: int, target_h: int) -> Image.Image:
    src_w, src_h = img.size
    target_ratio = target_w / target_h
    src_ratio = src_w / src_h

    if src_ratio > target_ratio:
        new_w = int(src_h * target_ratio)
        left = (src_w - new_w) // 2
        img = img.crop((left, 0, left + new_w, src_h))
    else:
        new_h = int(src_w / target_ratio)
        top = (src_h - new_h) // 2
        img = img.crop((0, top, src_w, top + new_h))

    return img.resize((target_w, target_h), Image.LANCZOS)


def generate_image(spec: dict, output_dir: str, skip_existing: bool = True) -> str:
    slug = spec["slug"]
    size_key = spec["size"]
    prompt = spec["prompt"]
    target_w, target_h = SIZES[size_key]

    out_path = os.path.join(output_dir, f"{slug}.png")
    if skip_existing and os.path.exists(out_path):
        print(f"  [skip] {slug}.png already exists", file=sys.stderr)
        return out_path

    pipe = get_pipeline()
    import torch

    seed_val = int(hashlib.md5(slug.encode()).hexdigest()[:8], 16)
    print(f"  [{slug}] Generating ({target_w}x{target_h})...", file=sys.stderr)
    t0 = time.time()

    torch.cuda.empty_cache()
    raw = pipe(
        prompt=prompt,
        height=1024,
        width=1024,
        num_inference_steps=8,
        generator=torch.Generator(device="cpu").manual_seed(seed_val),
    ).images[0]

    final = center_crop_to_ratio(raw, target_w, target_h)
    os.makedirs(output_dir, exist_ok=True)
    final.save(out_path, "PNG", optimize=True)

    elapsed = time.time() - t0
    print(f"  Saved {out_path} in {elapsed:.1f}s", file=sys.stderr)
    return out_path


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(
        description="Generate inline body images for amortcalc.io financial articles"
    )
    parser.add_argument(
        "--output",
        default="sites/amortcalc.io/public/images/blog",
        help="Output directory",
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="Generate all 12 body images",
    )
    parser.add_argument(
        "--test",
        action="store_true",
        help="Test: generate only the first body image",
    )
    parser.add_argument(
        "--slug",
        default=None,
        help="Generate a single image by slug",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing images",
    )

    args = parser.parse_args()
    output_dir = os.path.abspath(args.output)
    os.makedirs(output_dir, exist_ok=True)

    if args.test:
        specs = [BLOG_IMAGES[0]]
    elif args.slug:
        specs = [s for s in BLOG_IMAGES if s["slug"] == args.slug]
        if not specs:
            print(f"Unknown slug: {args.slug}", file=sys.stderr)
            sys.exit(1)
    elif args.all:
        specs = BLOG_IMAGES
    else:
        parser.print_help()
        sys.exit(0)

    print(f"Output: {output_dir}")
    print(f"Images to generate: {len(specs)}")

    generated = []
    for spec in specs:
        path = generate_image(spec, output_dir, skip_existing=not args.force)
        generated.append(path)

    print(f"\nDone — {len(generated)} image(s) in {output_dir}")


if __name__ == "__main__":
    main()
